### PR TITLE
Update troubleshooting faq with how to handle duplicate chunks

### PR DESCRIPTION
**Pull request by BerylKanali**
@jwokaty 
Here is the PR.
Towards https://github.com/Bioconductor/sweave2rmd/issues/46

### CODE REVIEW

**Comment by BerylKanali** [comment]
@jwokaty 
Any idea to solve the fail.

**Comment by jwokaty** [comment]
I think the failure is unrelated to your PR, so I made a separate issue #52 to handle it. 

Can you make the question clearer that it refers to duplicate code block names; otherwise, it might sound like entire block is a duplicate?

I also want to mention that it's a good habit to be brief and specific about about the commit message rather than using the same commit message for multiple commits. This habit will be helpful if you ever need to look through your commits to find a specific point.

Lastly, in your PR message, you can automatically link and close open issues if you use language such as `Close #46`. See  https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword#linking-a-pull-request-to-an-issue-using-a-keyword.

After you clarify the question, I think we can merge this.

**Comment by BerylKanali** [comment]
@jwokaty 
I refined the question, let me know if it is okay.

**Comment by jwokaty** [comment]
`BiocCheck` has a capital C for check. Please fix this and I will merge

**Comment by BerylKanali** [comment]
> `BiocCheck` has a capital C for check. Please fix this and I will merge

Done.
Closes https://github.com/Bioconductor/sweave2rmd/issues/46

**Pull request merged**
